### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Rudra00codes** [yesiamrajeev/Hacktoberfest2024#101]
Hi @yesiamrajeev ,

I noticed that this repository is part of **Hacktoberfest** but lacks a `CONTRIBUTING.md` file. Adding one could provide contributors with guidelines on how to contribute, which would be especially helpful for new contributors participating in Hacktoberfest. 

Would you be open to having this file added? I’d be happy to create and contribute the file if you'd like to assign this task to me. 

Thank you for your consideration! 😊

**Comment by yesiamrajeev** [comment]
Yeah go on!!!
Eat, Sleep & Contribute!!
HAPPY-HACKING!!

**Comment by Rudra00codes** [comment]
@yesiamrajeev, Thank you for assigning the issue!

I'll start working on the `CONTRIBUTING.md` file and submit a **pull request** shortly. If you have any specific guidelines or suggestions, feel free to let me know!

**Comment by yesiamrajeev** [comment]
Yes, add these things: make sure not to delete anyone else's files or modify anything unnecessarily in this repository. Your files should have the proper extensions and be placed inside a folder, star this repo. Lastly, ensure that you're open to make changes if required.

**Comment by Rudra00codes** [comment]
Thank you for the guidance!
I’ll make sure to follow these instructions and avoid any unnecessary modifications to the repository. I'll also ensure the files have the correct extensions and are placed in their respective folders. If any further changes are needed, I’ll be happy to adjust accordingly.

**Comment by Rudra00codes** [comment]
Got it! I'll add these instructions to the `CONTRIBUTING.md` file as you suggested. Thanks for the clarification!😅

**Comment by Rudra00codes** [comment]
@yesiamrajeev Thank you for the `greatcontribution` label! 😊  
I'm glad I could contribute. I'll go ahead and close the issue now. Just let me know if you need anything else! 👍

**Comment by yesiamrajeev** [comment]
Thank you so much for your help @Rudra00codes
