### ISSUE TITLE
want to add more cpp programs

### ISSUE THREAD

**Issue by Ananyajain2004** [yesiamrajeev/Hacktoberfest2024#112]
I want to add programs of data structures like tree ,stack, graph , binary search sliding window for placements.
@yesiamrajeev  please assign this issue to me under hacktoberfest 2024.

Please mark the hacktoberfest and hacktoberfest-accepted labels upon approving and merging the request.

**Comment by yesiamrajeev** [comment]
Sure go on!

**Comment by Khushi-Sarawagi** [comment]
Hey @yesiamrajeev , i recently added PRs for hollow diamond pattern in C++ and java for hacktoberfest. I would be greatful if you take a moment and review it.

**Comment by yesiamrajeev** [comment]
Kindly mention this issue in your PR so that i can review it properly.
