### ISSUE TITLE
 Add : Remove Duplicates from Sorted List

### ISSUE THREAD

**Issue by Amer-Mukhtar** [yesiamrajeev/Hacktoberfest2024#200]
Problem Statement:
Given the head of a sorted linked list, delete all duplicates such that each element appears only once. 
Return the linked list sorted as well.

Example:
Input: head = [1,1,2]
Output: [1,2]

Hello @yesiamrajeev  ! I’d love to contribute to this repository as part of Hacktoberfest 2024. Could you assign me to this issue and tag it with the Hacktoberfest label? Thanks in advance!

**Comment by yesiamrajeev** [comment]
Contribute quickly time is running out.
